### ISSUE TITLE
User requirements 2.2

### ISSUE THREAD

**Issue by vladiodes** [vladiodes/Workshop-on-Software-Engineering-Project#11]
Req 2.2.1: Info: buyers can get info about products/stores
Req 2.2.2: Searching for products (buyers)
Req 2.2.3: "Saving" products in the shopping basket (buyers)
Req 2.2.4: Checking the products in the shopping basket
Req 2.2.5: Buying the shopping cart

**Comment by IlayGo97** [comment]
Leaving purchase implementation until I can use supplier / payment systems.
